name: compilation

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  compilation-macos:

    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update brew
        run:  brew update && brew install gsl
      - name: Verify swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  
  compilation-linux:

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
