name: compilation

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
  workflow_dispatch:
  
jobs:
  compilation:
    name: Swift ${{ matrix.swift }} on ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        swift: ["5.10.1"]
    runs-on: ${{ matrix.os }}

    steps:
      - uses: swift-actions/setup-swift@v2
        with:
          swift-version: ${{ matrix.swift }}
      - name: Checkout
        uses: actions/checkout@v4
      - name: Update brew
        run:  brew update && brew install gsl
      - name: Verify swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
  
  compilation-linux:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Verify swift version
        run: swift --version
      - name: Build
        run: swift build
      - name: Run tests
        run: swift test
